version: "2"

services:
  mariadb:
    image: wodby/drupal-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./docker-runtime/mariadb:/var/lib/mysql
      - ./databases:/var/lib/mysql/databases

  php:
    image: wodby/drupal-php:5.6 # Allowed: 7.0, 5.6.
    restart: unless-stopped
    environment:
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: {{PROJ}}.dev.devbox21.com
      PHP_DOCROOT: docroot # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    volumes:
      - ./:/var/www/html
      - ./docker-runtime/drush:/root/.drush

  nginx:
    image: wodby/drupal-nginx
    restart: unless-stopped
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: php
      NGINX_DOCROOT: docroot # Relative path inside the /var/www/html/ directory.
      DRUPAL_VERSION: 7 # Allowed: 7, 8.
      VIRTUAL_HOST: {{PROJ}}.dev.devbox21.com
    volumes_from:
      - php
    networks:
      - proxy_net
      - default

  pma:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
      VIRTUAL_HOST: {{PROJ}}.pma.devbox21.com
    volumes:
      - ./docker-runtime/metro:/www/themes/metro
    networks:
      - proxy_net
      - default

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: {{PROJ}}.hog.devbox21.com
      VIRTUAL_PORT: 8025
    networks:
      - proxy_net
      - default

networks:
  proxy_net:
    external: true

#  redis:
#    image: redis:3.2-alpine

#  memcached:
#    image: memcached:1.4-alpine

#  memcached-admin:
#    image: phynias/phpmemcachedadmin
#    ports:
#      - "8047:80"

#  solr:
#    image: solr:5.5-alpine
#    volumes:
#      - ./docker-runtime/solr:/opt/solr/server/solr/mycores
#    ports:
#      - "8043:8983"

#  varnish:
#    image: wodby/drupal-varnish
#    depends_on:
#      - nginx
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#      VARNISH_MEMORY_SIZE: 256M
#      VARNISH_STORAGE_SIZE: 1024M
#    ports:
#      - "8044:6081" # HTTP Proxy
#      - "8045:6082" # Control terminal

